USE tokyo_draft;

INSERT INTO tokyo_draft (player_name, score) VALUES ('', '1');
INSERT INTO tokyo_draft (player_name, scored) VALUES ('', '1');
INSERT INTO tokyo_draft (player_name, scored) VALUES ('', '1');
INSERT INTO tokyo_draft (player_name, scored) VALUES ('', '1');
INSERT INTO tokyo_draft (player_name, devoured) VALUES ('', '1');
INSERT INTO tokyo_draft (player_name, scored) VALUES ('', '1');
INSERT INTO tokyo_draft(player_name, devoured) VALUES ('', '1');
INSERT INTO tokyo_draft(player_name, devoured) VALUES ('', '1');
INSERT INTO tokyo_draft (player_name, devoured) VALUES ('', '1');
INSERT INTO tokyo_draft (player_name, devoured) VALUES ('', '1');
INSERT INTO tokyo_draft (player_name, devoured) VALUES ('', '1');
INSERT INTO tokyo_draft (player_name, devoured) VALUES ('', '1');
INSERT INTO tokyo_draft (player_name, devoured) VALUES ('', '1');
INSERT INTO tokyo_draft (player_name, devoured) VALUES ('', '1');
INSERT INTO tokyo_draft (player_name, devoured) VALUES ('', '1');
INSERT INTO tokyo_draft(player_name, devoured) VALUES ('', '1');
INSERT INTO tokyo_draft(player_name, devoured) VALUES ('', '1');
INSERT INTO tokyo_draft (player_name, devoured) VALUES ('', '1');
INSERT INTO tokyo_draft (player_name, devoured) VALUES ('', '1');
INSERT INTO tokyo_draft (player_name, devoured) VALUES ('', '1');
INSERT INTO tokyo_draft (player_name, devoured) VALUES ('', '1');
INSERT INTO tokyo_draft (player_name, devoured) VALUES ('', '1');
INSERT INTO tokyo_draft (player_name, devoured) VALUES ('', '1');
INSERT INTO tokyo_draft (player_name, devoured) VALUES ('', '1');
INSERT INTO tokyo_draft(player, devoured) VALUES ('', '1');
INSERT INTO tokyo_draft(player_name, devoured) VALUES ('', '1');
INSERT INTO tokyo_draft (player_name, devoured) VALUES ('', '1');