USE tokyo_draft;

INSERT INTO tokyo_draft (burger_name, devoured) VALUES ('', '1');
INSERT INTO tokyo_draft (burger_name, devoured) VALUES ('', '1');
INSERT INTO tokyo_draft (burger_name, devoured) VALUES ('', '1');
INSERT INTO tokyo_draft (burger_name, devoured) VALUES ('', '1');
INSERT INTO tokyo_draft (burger_name, devoured) VALUES ('', '1');
INSERT INTO tokyo_draft (burger_name, devoured) VALUES ('', '1');
INSERT INTO tokyo_draft(burger_name, devoured) VALUES ('', '1');
INSERT INTO tokyo_draft(burger_name, devoured) VALUES ('', '1');
INSERT INTO tokyo_draft (burger_name, devoured) VALUES ('', '1');
INSERT INTO tokyo_draft (burger_name, devoured) VALUES ('', '1');
INSERT INTO tokyo_draft (burger_name, devoured) VALUES ('', '1');
INSERT INTO tokyo_draft (burger_name, devoured) VALUES ('', '1');
INSERT INTO tokyo_draft (burger_name, devoured) VALUES ('', '1');
INSERT INTO tokyo_draft (burger_name, devoured) VALUES ('', '1');
INSERT INTO tokyo_draft (burger_name, devoured) VALUES ('', '1');
INSERT INTO tokyo_draft(burger_name, devoured) VALUES ('', '1');
INSERT INTO tokyo_draft(burger_name, devoured) VALUES ('', '1');
INSERT INTO tokyo_draft (burger_name, devoured) VALUES ('', '1');
INSERT INTO tokyo_draft (burger_name, devoured) VALUES ('', '1');
INSERT INTO tokyo_draft (burger_name, devoured) VALUES ('', '1');
INSERT INTO tokyo_draft (burger_name, devoured) VALUES ('', '1');
INSERT INTO tokyo_draft (burger_name, devoured) VALUES ('', '1');
INSERT INTO tokyo_draft (burger_name, devoured) VALUES ('', '1');
INSERT INTO tokyo_draft (burger_name, devoured) VALUES ('', '1');
INSERT INTO tokyo_draft(burger_name, devoured) VALUES ('', '1');
INSERT INTO tokyo_draft(burger_name, devoured) VALUES ('', '1');
INSERT INTO tokyo_draft (burger_name, devoured) VALUES ('', '1');